app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls_books')),
]

app/books/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import User
from django.db import models

UserModel = get_user_model()


class Profile(models.Model):
    """
    - Обязательные поля email, имя, фамилия, номер телефона
    - Необязательные поля адрес, город
    """
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=30, unique=True)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        verbose_name = 'User Profile'
        verbose_name_plural = 'Users Profiles'


class AuthorModel(models.Model):
    author_name = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'

    def __str__(self):
        return self.author_name


class BooksModel(models.Model):
    book_title = models.CharField(max_length=200)
    book_isbn = models.CharField(max_length=20)
    book_author = models.ManyToManyField(AuthorModel)

    class Meta:
        verbose_name = 'Book'
        verbose_name_plural = 'Books'
        ordering = ['id']

    def __str__(self):
        return self.book_title


class BookSales(models.Model):
    book = models.ForeignKey(BooksModel, on_delete=models.SET_NULL, blank=True, null=True)
    sales = models.PositiveIntegerField(default=0, blank=True, null=True)
    sold_day = models.DateField(blank=True, null=True)

    class Meta:
        verbose_name = 'Books sales'
        verbose_name_plural = 'Books sales'

    def __str__(self):
        return self.book.book_title


class Notification(models.Model):
    sender = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    message = models.CharField(max_length=50, blank=True, null=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Notification'
        verbose_name_plural = 'Notifications'
        ordering = ['-id']

    def __str__(self):
        return self.message

app/books/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from .models import (Profile, BooksModel)


class SignUpForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'email', 'phone',
                  'address', 'city',)


class LogInForm(forms.Form):
    email_address = forms.EmailField(max_length=50, required=True)
    password = forms.CharField(max_length=50, required=True, )

    class Meta(AuthenticationForm):
        fields = ('email_address', 'password',)


class AddBookForm(forms.ModelForm):
    class Meta:
        model = BooksModel
        fields = ('book_title', 'book_author', 'book_isbn',)

app/books/views.py
import csv
from datetime import date
from http import HTTPStatus

from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages import get_messages
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from .forms import (SignUpForm, LogInForm, AddBookForm)
from .models import (BooksModel, BookSales, AuthorModel, Notification)
from .tasks import send_email
from .utils import work_with_notifications


class BooksMainPage(TemplateView):
    """ 3.2 Список книг """
    template_name = 'books/books_main_page.html'

    def get(self, request, *args, **kwargs):
        books = BooksModel.objects.all()
        paginator = Paginator(books, 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        response = {'page_obj': page_obj,
                    'messages': get_messages(request),
                    'msg_count': work_with_notifications(request.user, 'count'),
                    'is_authed': int(request.user.is_authenticated),
                    }
        return render(request=request, template_name=self.template_name, context=response)

    def post(self, request):
        data_to_search = request.POST['input_search']
        return redirect(to='search', search_it=data_to_search)


class SignUpPage(TemplateView):
    template_name = 'books/sign_up_page.html'

    def get(self, request, *args, **kwargs):
        response = {'form': SignUpForm(),
                    'messages': get_messages(request),
                    'is_authed': int(request.user.is_authenticated),
                    }
        return render(request=request, template_name=self.template_name, context=response)

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user_form = form.save(commit=False)
            user_first_name = form.cleaned_data.get('first_name')
            user_password = User.objects.make_random_password()
            user_email = form.cleaned_data.get('email')

            create_user = User.objects.create_user(username=user_first_name,
                                                   first_name=user_first_name,
                                                   last_name=form.cleaned_data.get('last_name'),
                                                   email=user_email,
                                                   password=user_password)
            create_user.save()

            user_form.user = create_user
            user_form.save()

            """ - После регистрации асинхронно выслать email с паролем """
            send_email.delay(user_first_name, user_email, user_password)

            messages.success(request, 'Registration success!')
            return redirect(to='ty-signup')
        else:
            messages.error(request, 'Error in Registration form validation!')
        return redirect(to='signup')


class LogInPage(TemplateView):
    """ Логин по email, password """
    template_name = 'books/login.html'

    def get(self, request, *args, **kwargs):
        response = {'form': LogInForm(),
                    'messages': get_messages(request),
                    'is_authed': int(request.user.is_authenticated),
                    }
        return render(request=request, template_name=self.template_name, context=response)

    def post(self, request):
        form = LogInForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email_address')
            password = form.cleaned_data.get('password')
            try:
                get_username = User.objects.get(email=email)
            except Exception as ex:
                print('! Error in User email) !\n%s' % ex)
                messages.error(request, 'Email is wrong!')
                return redirect(to='login')
            else:
                user = authenticate(request, username=get_username.username, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Login success!')
                    work_with_notifications(request.user, 'set', 'Login success!')
                    return redirect(to='main-page')
                else:
                    messages.error(request, 'Invalid Password!')
                    return redirect(to='login')
        else:
            messages.error(request, 'Error in Login form validation!')
            return redirect(to='login')


class TySignUpPage(TemplateView):
    template_name = 'books/ty_for_signup.html'

    def get(self, request, *args, **kwargs):
        return render(request=request, template_name=self.template_name,
                      context={'messages': get_messages(request),
                               'is_authed': int(request.user.is_authenticated), })


class BookStatisticPage(TemplateView):
    """ 3.1 Статистика """
    template_name = 'books/books_statistic.html'

    def get(self, request, *args, **kwargs):
        """ - Книг продано всего """
        books_sales = BookSales.objects.all()
        total_sales = books_sales.aggregate(Sum('sales'))['sales__sum']

        """ - Книг продано за прошлый месяц """
        months = [i for i in range(1, 13)]
        month_now = date.today().month
        sales_last_month = books_sales.filter(
            sold_day__month=months[month_now - 2]).aggregate(Sum('sales'))['sales__sum']

        books_total = BooksModel.objects.all()

        """ - Продано книг по авторам (%) """
        author_data = []
        if total_sales:
            authors = AuthorModel.objects.all()
            for author in authors:
                author_books = books_total.filter(book_author=author)
                author_sales = 0
                for book in author_books:
                    sales__sum = books_sales.filter(book=book).aggregate(Sum('sales'))
                    if any(sales__sum.values()):
                        author_sales += sales__sum['sales__sum']
                author_sales_percent = round(100 * (author_sales / total_sales), 2)
                author_data.append([author.author_name, author_sales_percent])

        author_data.sort(key=lambda s: s[1], reverse=True)

        """ - Продано книг  """
        books_sold = 0
        for book in books_total:
            is_sold = books_sales.filter(book=book)
            if any(is_sold):
                books_sold += 1
        all_books = books_total.count()
        if all_books:
            sold_vs_all_books = round(100 * (books_sold / all_books), 2)
        else:
            sold_vs_all_books = 0

        response = {'total_sales': total_sales,
                    'sales_last_month': sales_last_month,
                    'author_data': author_data,
                    'books_sold': books_sold,
                    'all_books': all_books,
                    'sold_vs_all_books': sold_vs_all_books,
                    'msg_count': work_with_notifications(request.user, 'count'),
                    'is_authed': int(request.user.is_authenticated),
                    }
        return render(request=request, template_name=self.template_name, context=response)


def search_page(request, search_it):
    """ - Общий фильтр по названию книги, имени автора, артикулу """
    if request.method == 'GET':
        work_with_notifications(request.user, method='set', msg="search: %s" % search_it)

        data = {'found_books': BooksModel.objects.filter(book_title__contains=search_it),
                'found_authors': AuthorModel.objects.filter(author_name__contains=search_it),
                'found_isbn': BooksModel.objects.filter(book_isbn__contains=search_it),
                'search_it': search_it,
                'msg_count': work_with_notifications(request.user, 'count'),
                'is_authed': int(request.user.is_authenticated),
                }
        return render(request=request, template_name='books/book_search.html', context=data)


class NotificationPage(TemplateView):
    """ - Персональные нотификации. Выводить не больше 5 ранее виденных.
    Выделить впервые увиденные нотификации
    """
    template_name = 'books/books_notification.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            user_msg = work_with_notifications(request.user, 'get')
            Notification.objects.filter(sender=request.user, is_read=False).update(is_read=True)

            old_notif = Notification.objects.filter(sender=request.user, is_read=True)
            msg_old_5 = [i.message for i in old_notif[:5]]

            response = {'user_msg': user_msg,
                        'user': request.user,
                        'msg_old_5': msg_old_5,
                        'is_authed': int(request.user.is_authenticated),
                        'msg_count': work_with_notifications(request.user, 'count'),
                        }
        else:
            messages.warning(request, "Unauthorized users can't see notifications.")
            response = {'is_authed': 0,
                        'messages': get_messages(request),
                        }
        return render(request=request, template_name=self.template_name, context=response)


def logout_user(request):
    logout(request)
    messages.success(request, 'Log out successful!')
    return redirect(to='main-page')


class ExportBooksPage(TemplateView):
    template_name = 'books/books_export.html'

    def get(self, request, *args, **kwargs):
        response = {'is_authed': int(request.user.is_authenticated),
                    'msg_count': work_with_notifications(request.user, 'count'),

app/books/templates/books/book_search.html
{% extends 'books/books_template.html' %}

{% block title %}
    Search
{% endblock %}

{% block content %}

    <h3>Results what was found for the request "{{ search_it }}"</h3>

    <h4>Books:</h4>
    {% for found_book in found_books %}
        <p>{{ found_book.book_title }}</p>
    {% empty %}
        <p>Nothing was found</p>
    {% endfor %}

    <h4>Authors:</h4>
    {% for found_author in found_authors %}
        <p>{{ found_author.author_name }}</p>
    {% empty %}
        <p>Nothing was found</p>
    {% endfor %}

    <h4>Books with ISBN:</h4>
    {% for book in found_isbn %}
        <p>{{ book.book_isbn }}</p>
    {% empty %}
        <p>Nothing was found</p>
    {% endfor %}

{% endblock %}

app/books/templates/books/books_add.html
{% extends 'books/books_template.html' %}

{% block title %}
    Add Book
{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}

    <form>
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-info" type="submit" id="btn_add">Add Book</button>
    </form>

    <script>
        var token = '{{csrf_token}}';

        $('#btn_add').on('click', function () {
            var book_title = $('#id_book_title').val();
            var book_author = $('#id_book_author').val();
            var book_isbn = $('#id_book_isbn').val();

            $.ajax({
                headers: {"X-CSRFToken": token},
                method: 'POST',
                url: "{% url 'add-book' %}",
                data: {
                    'book_title': book_title,
                    'book_author': book_author,
                    'book_isbn': book_isbn,
                },
                dataType: 'json',
                success: function (data) {
                    console.log('success!', data);
                    if (data.redirect) {
                        window.location.href = data.redirect;
                    }
                },
                error: function (error) {
                    console.log('error!');
                },
            });

            var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
    </script>

{% endblock %}

app/books/templates/books/books_export.html
{% extends 'books/books_template.html' %}

{% block title %}
    Export
{% endblock %}

{% block content %}

    <form method="post" class="text-center">
        {% csrf_token %}
        <button class="btn btn-info" type="submit" id="some_btn">
            Download CSV file with all books & authors (titles + names)
        </button>
    </form>

    <script>
        var token = '{{csrf_token}}';

        $('#some_btn').on('click', function () {
            $.ajax({
                headers: {"X-CSRFToken": token},
                method: 'POST',
                url: "{% url 'book-export' %}",
                data: {'some-data': 'ajax'},
                dataType: 'json',
                success: function (data) {
                    console.log('success!', data);
                    if (data.redirect) {
                        window.location.href = data.redirect;
                    }
                },
                error: function (error) {
                    console.log('error!', error);
                },
            });

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });

        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
    </script>

{% endblock %}

app/books/templates/books/books_main_page.html
{% extends 'books/books_template.html' %}

{% block title %}
    Books
{% endblock %}

{% block content %}

    <div>
        <h3>Books list</h3>

        <div class="input-group mb-3">
            <input class="form-control rounded" id="search_book" type="text" placeholder="search on this page"
                   aria-label="search on this page">
            <p class="m-2">or</p>
            <form method="post" class="form-inline">
                {% csrf_token %}
                <input type="text" class="form-control rounded-left" placeholder="search in the data base"
                       aria-label="Search in the data base" aria-describedby="button-addon2" name="input_search">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Go</button>
                </div>
            </form>
        </div>

        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">ISBN</th>
            </tr>
            </thead>
            <tbody id="book_table">
            {% for book in page_obj %}
                <tr>
                    <th scope="row">{{ forloop.counter0|add:page_obj.start_index }}</th>
                    <td>{{ book.book_title }}</td>
                    <td>{% for author in book.book_author.all %}{{ author }}, {% endfor %}</td>
                    <td>{{ book.book_isbn }}</td>
                    <td><a href="{% url 'one-book' book.pk %}">Link</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <nav aria-label="Page navigation example" class="text-center">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                {% endif %}
                <span class="current m-2">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last
                        &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>

    </div>

    <script>
        {#// Perform a case-insensitive search for items in a table#}
        $(document).ready(function () {
            $("#search_book").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#book_table tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>


{% endblock %}

app/books/templates/books/books_notification.html
{% extends 'books/books_template.html' %}

{% block title %}
    Notifications
{% endblock %}

{% block content %}

    <h4>Your notifications, {{ user|default:'NoName' }}:</h4>
    {% if user_msg %}
        {% for message in user_msg %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}

    {% if msg_old_5 %}
        {% for message in msg_old_5 %}
            <div class="alert alert-light" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}

{% endblock %}

app/books/templates/books/books_statistic.html
{% extends 'books/books_template.html' %}

{% block title %}
    Statistic
{% endblock %}

{% block content %}

    <ul>
        <li>Total sales: {{ total_sales|default:'No data' }}</li>
        <li>Sold last month: {{ sales_last_month }}</li>
        <li>Total books: {{ all_books }}, books sold: {{ books_sold }} ({{ sold_vs_all_books }} %)</li>
    </ul>

    <h4>Sales per Author:</h4>
    <input class="form-control" id="search_book" type="text" placeholder="search on the page ...">
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Author</th>
            <th scope="col">Sales, %</th>
        </tr>
        </thead>
        <tbody id="book_table">
        {% for author, sales in author_data %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ author }}</td>
                <td>{{ sales }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <script>
        $(document).ready(function () {
            $("#search_book").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#book_table tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

{% endblock %}

app/books/templates/books/books_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'books/css/my_css.css' %}">

    <title>{% block title %}Title{% endblock %} - Test Task</title>
</head>
<body>

<div class="container bg-light">

    <div class="bg-dark my-nav-margin">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand" href="{% url 'main-page' %}">Books</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'main-page' %}">Books list</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'statistics' %}">Books statistic</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book-export' %}">Export books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'books-add' %}">Add book</a>
                    </li>
                </ul>

                <form class="form-inline my-2 my-lg-0">
                    <a class="btn btn-info mr-sm-2" href="{% url 'notifications' %}">
                        Notifications <span class="badge badge-warning">{{ msg_count|default:'0' }}</span>
                    </a>
                    {% if is_authed %}
                        <a class="btn btn-success" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a class="btn btn-success mr-sm-2" href="{% url 'login' %}">Login</a>
                        <a class="btn btn-primary" href="{% url 'signup' %}">Register</a>
                    {% endif %}
                </form>
            </div>
        </nav>
    </div>
    <br>

    <div>
        {% block content %}{% endblock %}
    </div>

</div>

<div class="message-include">
    {% include 'books/messages.html' %}
</div>

</body>
</html>

app/books/templates/books/login.html
{% extends 'books/books_template.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Login
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Login</button>
    </form>

{% endblock %}

app/books/templates/books/messages.html
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible shadow border" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
{% endfor %}

app/books/templates/books/one_book.html
{% extends 'books/books_template.html' %}

{% block title %}
    {{ book.book_title }}
{% endblock %}

{% block content %}

    <p>book title: {{ book.book_title }}</p>
    <p>book authors: {% for author in book.book_author.all %}{{ author }}, {% endfor %}</p>
    <p>book isbn: {{ book.book_isbn }}</p>

    <a class="btn btn-success" href="{% url 'main-page' %}">Back</a>

{% endblock %}

app/books/templates/books/register_page.html
{% extends 'books/books_template.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Register
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Register</button>
    </form>

{% endblock %}

app/books/templates/books/sign_up_page.html
{% extends 'books/books_template.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Sign Up
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Sign up</button>
    </form>

{% endblock %}

app/books/templates/books/ty_for_signup.html
{% extends 'books/books_template.html' %}

{% block title %}
Thank you for Registration
{% endblock %}

{% block content %}
    <p>Thank you for registering to our site!</p>
    <p>Your password was sent to your email</p>

    <p>Check it and <a class="btn btn-success" href="{% url 'login' %}">Login</a></p>

{% endblock %}